#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/haproxy/functions"

# install haproxy
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\* socat

# give access
sudo cat<<EOF > /etc/sudoers.d/dokku-haproxy
%dokku ALL=(ALL) NOPASSWD:/bin/systemctl reload-or-restart haproxy,/bin/systemctl start haproxy
EOF

chmod 0440 /etc/sudoers.d/dokku-haproxy

# set new haproxy config location
mkdir -p /var/lib/dokku-haproxy
touch /var/lib/dokku-haproxy/haproxy.cfg
sudo sed -i 's/#CONFIG=\"\/etc\/haproxy\/haproxy.cfg\"/CONFIG=\"\/var\/lib\/dokku-haproxy\/haproxy.cfg\"/g' /etc/default/haproxy

# give access
chown dokku:dokku /var/lib/dokku-haproxy
chown dokku:dokku /var/lib/dokku-haproxy/*

case "$DOKKU_DISTRO" in
  ubuntu)
    sudo /bin/systemctl start haproxy
    ;;
esac

haproxy_reload
